{"version":1,"defects":{"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_client_id_is_invalid":3,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_token_is_expired":4,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_creates_valid_resource_owner":3,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_should_return_token_claims_on_successful_validation":5,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_token_is_from_future":3,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_creates_valid_access_token":3,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_should_throw_exception_for_invalid_keys":4},"times":{"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_creates_access_token":0.113,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_client_id_is_invalid":0.073,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_token_is_expired":0.057,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_token_is_from_future":0.111,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_throws_runtime_exception_when_issuer_is_invalid":0.093,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_creates_valid_resource_owner":0.046,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_should_return_token_claims_on_successful_validation":0.103,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_creates_valid_access_token":0.095,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_correctly_serializes_the_access_token":0.069,"TheNetworg\\OAuth2\\Client\\Tests\\Provider\\AzureTest::it_should_throw_exception_for_invalid_keys":0.065}}